### ISSUE TITLE
Everything is done, but no BG showed on the watchface

### ISSUE THREAD

**Issue by jihrichard** [miguelavh/Watchdrip-Xiaomi#1]
I have followed the instructions to successfully set up all the settings. The BG displays on the watchdrip and watchdrip-xiaomi, and I also downloaded the watchface but no BG as you can see the picture below. Don't know why? Thank you in advance.

![1730613525259](https://github.com/user-attachments/assets/41268408-d794-4739-880c-6087f08902cf)

**Comment by miguelavh** [comment]
Hi, can you check some  permissions on mi fitness app, go to profile/device permissions/watchdripXiaomi and check that all is checked?...
![Screenshot_20241103_094905_Mi Fitness](https://github.com/user-attachments/assets/46d3ab7c-5fa6-4a64-95b2-e48372178171)

**Comment by jihrichard** [comment]
This permission are all checked by default ...

![1730633752775](https://github.com/user-attachments/assets/74e22c04-de72-462e-bc20-0079ea8cdaa5)

**Comment by miguelavh** [comment]
It's ok... Can you open  watchdripxiaomi app on your phone and send me screenshot It would be something like this
![Screenshot_20241103_124221_WatchdripXiaomi](https://github.com/user-attachments/assets/20538f53-23ed-4dc1-9b1f-e7a0234242ab)

**Comment by jihrichard** [comment]
![Screenshot_20241103-194714](https://github.com/user-attachments/assets/cc144271-7cbd-490b-9f83-3cf8eac38e1d)

**Comment by miguelavh** [comment]
Ok, coms is working... Do you activate all permissions on mi-fitness app? Try please and disable battery restrictions too

**Comment by jihrichard** [comment]
I activate all permissions and disable the battery restrictions, but still no BG showed in the band. Then I uninstalled the mifitness and watchdrip-xiaomi, reinstall again, check all the settings and download the band display. Then it works!!! 😁😁 

Thank you for your help 

![1730635831556](https://github.com/user-attachments/assets/11631004-c285-49d4-b7cd-40d03f9ccbae)

**Comment by miguelavh** [comment]
Great!!! One technical mistery... Thanks to you...
