### ISSUE TITLE
No data transfer between the phone and the band

### ISSUE THREAD

**Issue by ledrexter** [miguelavh/Watchdrip-Xiaomi#2]
Hi, 
I followed the instructions installink MiFitness_3.33.6i_m0tral_v139.apk and watchdrip-xiaomi on both the phone and the band.
I also installed the two watchfaces on the band.
I see the BG values in the watchdrip-xiaomi on the phone but the values are 0s on the watchface.
Could you please help me bring the connection up?

Thanks,
Petar

**Comment by miguelavh** [comment]
Hi, Do you activate all permissions on mi-fitness app? Try please and disable battery restrictions too at mi-fitness app and watchdrip-xiaomi app on phone...

**Comment by ledrexter** [comment]
Hi, 
yes, I have enabled all permissions and  disabled the battery optimization for  all applications.
Yesterday I tried to cleaning up the cash and the data and reinstalling MiFitness_3.33.6i_m0tral_v139.apk and WatchDritpXiaomi.apk  and setting them up once again but it did not resolve the issue.

Thanks in advance,
Petar

Attachedsnapshots:
![image](https://github.com/user-attachments/assets/e97b11b8-d3ce-48f7-ac78-ad6e6a489e83)
![image](https://github.com/user-attachments/assets/df8be3d2-ca1a-4ec4-b4dc-581f2597a04c)
![image](https://github.com/user-attachments/assets/e8e79418-c625-4135-b571-e8ac635a258e)
![image](https://github.com/user-attachments/assets/54c03212-6595-4ae9-8b7c-68b447466947)
![image](https://github.com/user-attachments/assets/b6b7e964-7dda-4068-94f1-e3b7e9c31731)
![image](https://github.com/user-attachments/assets/1775b7b9-0341-468f-b9da-ac63aafee44c)

**Comment by miguelavh** [comment]
try uninstall and install watchdrip-xiaomi app on watch... and close (info/force close) and open again watchdrip-xiaomi app on phone

**Comment by ledrexter** [comment]
Thanks a lot,
This resolved the issue. I see the BG values:
![image](https://github.com/user-attachments/assets/e671fd36-457f-422a-929c-77d5c6fca9df)
![image](https://github.com/user-attachments/assets/6c49a7f8-6732-4554-91b1-240a4d9479ee)

**Comment by ledrexter** [comment]
Actually there is some new issue.
I changed the watchfaces one-two times and now the WatchDrip+ Graph is showing some log in the background:
![image](https://github.com/user-attachments/assets/ec4d599d-02ae-4954-85e2-ffab78b1d0aa)

**Comment by miguelavh** [comment]
OK, It would be a problem with mmol data painting... I'll check... thank you

**Comment by miguelavh** [comment]
Hi I have made one test with mmol configured and worked right... It would be a problem with watchdrip version at phone... latest published have a problem with graph data in mmol, this version have fixed that... try it please https://www.dropbox.com/scl/fi/gepkpekh4gm3wbiu37awr/WatchDrip_v0.3.2.apk?rlkey=ftbcn1tj3dn4o8d1bc9xmj0ne&st=isnonr0e&dl=1

**Comment by ledrexter** [comment]
Hi,
I'm really sorry for the delayed response.
I somehow missed the email.

I updated WatchdripXiaomi.apk  from your link and I restarted both application on the phone and the band but the situration is still the same.
There is no graph but there are errors/warnings about the graph.

What I also observe is that both watchfaces there are like two floating points in the BG value:
![image](https://github.com/user-attachments/assets/8723c710-86a6-4d82-ba03-8ad8f0d640fa)
![image](https://github.com/user-attachments/assets/497e6a0c-1d1f-470a-9188-48e79d64844f)

**Comment by ledrexter** [comment]
Once I observed there was a visualized graph in between the messages, but later it disappeared and now I only have the thresholds in browns and red:
![image](https://github.com/user-attachments/assets/dcffea3f-6c14-4639-8457-8093941bdd5b)

**Comment by miguelavh** [comment]
Yes, I'm checking... later I'll tell you to test new watchfaces version...

**Comment by miguelavh** [comment]
> Once I observed there was a visualized graph in between the messages, but later it disappeared and now I only have the thresholds in browns and red: ![image](https://private-user-images.githubusercontent.com/51510015/385763937-dcffea3f-6c14-4639-8457-8093941bdd5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MTAxNDAsIm5iZiI6MTczMTUwOTg0MCwicGF0aCI6Ii81MTUxMDAxNS8zODU3NjM5MzctZGNmZmVhM2YtNmMxNC00NjM5LTg0NTctODA5Mzk0MWJkZDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDE0NTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NjNmYzBlOWU2Y2FiNTExZDhmMWQ2OTI4ZGQzZTQyYzdmN2U4MDk2NmI4OTUyOTFkYzk1NjYxZDNhMThiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OpPXkTuXfg-bdywRwn7art-EHTVO5dpe6No1vtoKA9k)

Hi again, I have updated two watchfaces... please uninstall two watchfaces and reinstall... tell me if all is working...

**Comment by ledrexter** [comment]
It is now perfect!
Thanks a lot, just one more question.
Although I have disabled all optimizations etc, the same way I have done for aaps, xdrip and WatchDrip+ I observe WatchdripXioami stops once a day.
Is there a log file or another way I can inevstigate how come it is killed or crashed ?

![image](https://github.com/user-attachments/assets/f19e7d76-7192-47dd-a6fc-1fd05f3b0a27)
![image](https://github.com/user-attachments/assets/35bb3608-e505-41e2-87d1-ffa41eea3305)

**Comment by miguelavh** [comment]
Watchdrip-Xiaomi have a service running at background... only you must disable all battery restrictions... one more thing you can do is to lock this app... Depending on the mobile brand (xiaomi have a lot of restrictions), It can go into some optimization and disable or stop the app... but if you lock the app it keeps running...

**Comment by ledrexter** [comment]
I am using Xiaomi 11T pro and here is the setup of the Watchdrip-Xiaomi:
locked in the resent apps and 
and disabled battery optimization
pause app activity if unused disabled 

![image](https://github.com/user-attachments/assets/4fe0ac61-be2b-4ff0-aa66-bb39ac7acfcb)
![image](https://github.com/user-attachments/assets/59a12e55-96c5-455e-9a03-99a771c4f092)

**Comment by miguelavh** [comment]
It's perfectly configured... check If mi-fitness have all permissions and battery optimizations disabled...

**Comment by ledrexter** [comment]
It is now two days since I installed the new watchface and I had not need to start the  Watchdrip-Xiaomi.
It could be it was being terminated because of the watchefaces issues.
I will get back if any issue.
I am closing this issue for now.
Thanks for you support!
