### ISSUE TITLE
The watch face cannot display negative temperature

### ISSUE THREAD

**Issue by ledrexter** [miguelavh/Watchdrip-Xiaomi#3]
Hi,

I think there is some issue with the value of the displayed temperature of the weather.
Is it a signed value?

Today the temperatures dropped below 0 a and the temp was missing until it get back to 0.
PS Sorry for the blurry picture, I have just realized it is not clear :(
Snapshots are bellow:
![image](https://github.com/user-attachments/assets/63ba6094-e8a2-409c-bb04-f910ce786bcd)
![image](https://github.com/user-attachments/assets/7b2aaf63-9ed0-421e-86ee-a61d2c4cf578)
The digit are back once the value is positive:
![image](https://github.com/user-attachments/assets/21c48a8d-712e-4d9d-9e84-891c06098ab1)

Regards,
Petar

**Comment by miguelavh** [comment]
I'll check...

**Comment by miguelavh** [comment]
I have updated graph watchface, can you uninstall and install again? If all is OK I'll update Big watchface too...

**Comment by ledrexter** [comment]
Thanks for the update.
I will need to wait for the weather to drop below 0 again and I will let you know.

**Comment by ledrexter** [comment]
Hi,
I can confirm the issue is resolved for the watchface with the graph.

![image](https://github.com/user-attachments/assets/fdf1423b-1e11-48a3-878b-787c1a46ced6)
![image](https://github.com/user-attachments/assets/1782cf77-190a-4fbb-a9bf-83a5ba4aca97)


Thanks for the fix!

Regards,
Petar

**Comment by miguelavh** [comment]
Great!! I have updated Big Watchface too, only uninstall and install again...
